name: 'Pack and Publish .NET NuGet Package for .net10.0' 
description: 'Restores, builds, packs, and publishes a .NET NuGet package to GitHub Packages'
inputs:
  dotnet-version:
    description: 'Version of .NET to use'
    required: false
    default: '10.0.x'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.4.0'

    - name: Cache NuGet packages        # Try to find if a build cached packages. Maybe the build_check. This saves time
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          nuget-${{ runner.os }}-

    - name: Cache build output      # Try to find if a build cached comiled files. Maybe the build_check. This saves time
      uses: actions/cache@v4
      with:
        path: |
          **/bin
          **/obj
        key: build-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4.1.0
      with:
        overrideConfig: |
          workflow=TrunkBased/preview1
          commit-message-incrementing=Enabled
          tag-prefix=v
          increment=Patch

    - name: Show extracted version
      run: echo "Version is ${{ steps.gitversion.outputs.SemVer }}"
      shell: bash


    # Ensure that the github-Surimi-project NuGet source is configured. The standard GITHUB_TOKEN is used. It's automatically created by GitHub Actions and is available as 'github.toke'
    # So you don't have to pass it to this action explicitly. (because 'secrets', and subsequently 'secrets.GITHUB_TOKEN' is not accessible in reusable workflows)
    - name: Ensure github-Surimi-project NuGet source
      run: |
        if dotnet nuget list source | grep -q "github-Surimi-project"; then
          dotnet nuget remove source github-Surimi-project
        fi
        dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --name "github-Surimi-project" \
          --username ${{ github.repository_owner }} \
          --password ${{ github.token }} \
          --store-password-in-clear-text
      shell: bash

    - name: List NuGet data sources
      run: dotnet nuget list source --format detailed
      shell: bash

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build
      run: dotnet build --configuration Release
      shell: bash

    - name: Pack NuGet package
      run: dotnet pack --configuration Release --output ./nuget /p:PackageVersion=${{ steps.gitversion.outputs.SemVer }}
      shell: bash

    - name: List NuGet output files
      run: dir ./nuget
      shell: bash

    - name: Publish to GitHub Packages
      run: |
        for file in ./nuget/*symbols.nupkg; do
          if [ -f "$file" ]; then
            dotnet nuget push "$file" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ github.token }} --skip-duplicate
          fi
        done
      shell: bash
